<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Adam">
<meta name="dcterms.date" content="2017-07-31">

<title>Exploring Violent Crime in Louisville – Semi-Random Data Musings</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-f33991cf3c59b7de71e019b8ce5d8602.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Semi-Random Data Musings</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/houlad"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://mastodon.social/@adam_houl"> <i class="bi bi-mastodon" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Exploring Violent Crime in Louisville</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">R</div>
                <div class="quarto-category">data visualization</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Adam </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">July 31, 2017</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Over the past year Louisville’s local news seems like it has been increasingly dominated by crime news. Whether it was riots, teens running rampant or a record number of homicides, you got the impression that our little city was inching toward a future resembling a scene from Mad Max. Is it no longer safe to walk the streets? Do we need to barricade the doors and booby trap the lawn? Or is this crime increase overblown and not, in fact, the start of the apocalypse. This is the first in, hopefully, a series of posts that will dive into the data and investigate just how bad crime has gotten in our fair city.</p>
<p>Luckily, Louisville has a rich crime dataset that is open and ripe for analysis. Although records extend back to the 1920’s, the data is very sparse up until around 2004. For the purposes of this investigation, I will look at crime records spanning 2005-2016. Given the breadth of the available data, I will need to split the analysis into components in order to go into any detail. This first post will deal strictly with violent crime.</p>
</section>
<section id="overview-of-violent-crime" class="level1">
<h1>Overview of Violent Crime</h1>
<p>2016 was a year with a record number of homicides in Louisville. Seeing these reports every day was the genesis of this analysis, so it is only fitting to begin by exploring the most visceral of criminal offenses–violent crime. There are four offenses the FBI considers violent crime – murder and nonnegligent manslaughter, forcible rape, robbery and aggravated assault. As can be seen in the figure below, in the aggregate, a minor increase is apparent. The red trend line fit to the data has a slope of about 27 meaning (with this enormously oversimplified model) that we are seeing an increase of about 27 violent crime reports every year. However, as you can already see from the graph, the year-to-year variation is substantial making a simple trend line like this highly suspect.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/violent_crime_trend_plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>If numbers are more your thing, you can see that violent crime is up about 12.8% from the 12 year mean, and is actually at an all-time high in 2016.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Change_from_2015</th>
<th style="text-align: left;">Change_from_Max</th>
<th style="text-align: left;">Change_from_Mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">7.1%</td>
<td style="text-align: left;">0%</td>
<td style="text-align: left;">12.8%</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="is-the-increase-in-violent-crime-significant" class="level2">
<h2 class="anchored" data-anchor-id="is-the-increase-in-violent-crime-significant">Is the Increase in Violent Crime Significant</h2>
<p>So it does seem like we are seeing an upward trend in violent crime. But looking at the graph, it sure doesn’t appear to be the end of the world scenario the news is predicting. Was 2016 even a significant increase from the general trend of the past decade? This is a more complicated question than it appears. Are we asking about 2016 compared to the running average from the previous 11 years(2005-2015)? Or are we asking whether 2016 counts are different from 2015(or different from 2005 for that matter)? Let’s look at both and see what they tell us.</p>
<p>First, let’s look at the breakdown of violent crime by day. Both the histogram and the density plot show the same information, just in different ways. What we can see on both is that right around 10 violent crimes per day is most common. What the density plot shows a little better is the slight right-skewed shape to the distribution. It is approximately normal(the dotted red line), but with that right-skew which indicates higher counts have more probability associated with them.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/daily_count_hist/dist-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="violent-crime-distributions-broken-down-by-year" class="level3">
<h3 class="anchored" data-anchor-id="violent-crime-distributions-broken-down-by-year">Violent Crime Distributions Broken Down By Year</h3>
<p>Looking at the same data, but broken into years, we can see that, while there is variation, it is not obvious whether there has been a shift in the distribution–which would indicate a change in violent crime.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/daily_count_all_years-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>However, when we compare 2016 versus 2005-2015, a clear shift in the distribution is visible.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/daily_count_all_vs_2015-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>With all this in hand, can we give a more definitive answer as to whether violent crime has increased? We can if we ask the question ‘Is the mean count of violent crimes per day in 2016 different from the mean count of violent crimes in the period 2005-2015’? Using a t-test we get the following.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  sums_2016$count
t = 6.7818, df = 363, p-value = 4.83e-11
alternative hypothesis: true mean is not equal to 10.30027
95 percent confidence interval:
 11.34913 12.20582
sample estimates:
mean of x 
 11.77747 </code></pre>
</div>
</div>
<p>That is a lot of information, but we want to focus on two values–the p-value and the confidence interval. The test is asking if the ‘true’ mean number of violent crimes per day is 10.3, how likely is it that we see a random sample(the data from 2016) with a mean of 11.78. The p-value of 4.83e-11 is basically the probability of seeing this result. So in this case, the result is almost unheard of if it were just due to chance(i.e., there is a real difference). Looking at the confidence interval, if our 2005-2015 mean of 10.3 was contained within it would indicate that we could not be confident 2016’s results weren’t due to random fluctuation. Both of these values indicate that the mean of 2016 is different from, and in this case larger than, the 2005-2015 mean.</p>
<p>With all of that said, it is important to keep in mind the difference between statistical and practical significance. While there does appear to be a statistically significant change in the daily violent crime count, that does not necessarily mean there is a practically significant difference. Looking at absolute numbers, we are looking at a difference of 1.48. Is 1.48 more violent crimes per day cause for alarm? Well, that depends on a lot of factors, most of which I won’t get into here. But for illustration purposes I will point out that according to the latest census <a href="https://www.census.gov/quickfacts/table/PST045214/21111">information</a>, Louisville’s population grew 3.3% from 2010 to 2016. It seems logical that an increase in population will also result in an increase in absolute crime numbers. If you normalize for population increase, do you still see a significant change? I will leave that analysis to the reader.</p>
</section>
</section>
</section>
<section id="mapping-violent-crime-locations" class="level1">
<h1>Mapping Violent Crime Locations</h1>
<p>It is also informative to see where the violent crimes are centered in Louisville. Although this greatly simplifies the issue, if crimes are highly concentrated in certain areas you may have less to worry about if you live across town than if you happen to live right in the middle of those neighborhoods. After some additional data <a href="https://github.com/houlad/LouisvilleCrime/blob/master/louisville_raw_data_and_geocoding.R">preparation</a> and <a href="https://github.com/houlad/LouisvilleCrime/blob/master/LouisvilleCrime/Louisville_Crime_Geocoding.R">geocoding</a> it is simple enough to see where violent crime is taking place.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/crime_map1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It should be immediately obvious that there is one major and one minor hotspot. Let’s zoom in to those areas and see if we can detect a change over time.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/crime_map2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>When we zoom in and break it down by year, we can see a minor, but visible, increase in the intensity of the heat map. Particularly from 2012-2016 we see a brightening of intensity in downtown Louisville. In 2016 in particular, it appears that we have expanding the downtown crime bubble ever so slightly, though this would warrent further analysis to determine anything concretely. What becomes apparent when viewing these breakdowns though is just how localized the violent crime is. When broken down by zip codes, it is shocking how skewed the numbers are. Just 6 of Louisville’s 66 zip codes account for 49.6% of all violent crime in Louisville. If we bump that up to the 12 zip codes, we cover 76.01% of violent crimes.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/zip_code_plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="high-crime-zip-codes" class="level2">
<h2 class="anchored" data-anchor-id="high-crime-zip-codes">High Crime Zip Codes</h2>
<p>Finally, let’s take a quick look at the worst ten zip codes in terms of violent crime and see if maybe a change within those areas is why we are seeing marginally higher violent crime numbers in the city as a whole.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/worst_zip_codes-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Examining the plot, we have 4 of the 10 zip codes showing a slight downward trend, with the remaining 6 trending upward. Unfortunately, 40211 is in a league of its own, showing a dramatic increase in violent crime since 2005. With 5 of the 6 top zip codes showing increasing trends, I wanted to determine whether they were the reason for the increase in violent crime. Is violent crime just increasing in those areas or is the problem more widespread?</p>
<p>The plot below shows that by excluding the top 6 violent crime zip codes–which, remember, account for nearly 50% of all Louisville’s violent crime–we actually see a dramatically different picture.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/40211_exclusion-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We go from a very clear increase over the years to essentially a flat trend. If we perform the same t-test as before, we still have a significant finding, but the result is much more borderline. The 2005-2015 mean of 5.25 is quite close to falling within the 95% confidence interval in this case. So we can with reasonable confidence say that violent crime has increased marginally, but for the vast majority of Louisville’s residents, this increase may not actually be practically significant. Isolated pockets within the city are bearing the brunt of this increase, while large portions of the city are left with little to no increase at all.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  sums_2016_no_top_6$count
t = 3.6664, df = 360, p-value = 0.000283
alternative hypothesis: true mean is not equal to 5.254036
95 percent confidence interval:
 5.509984 6.102205
sample estimates:
mean of x 
 5.806094 </code></pre>
</div>
</div>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>As with most socioeconomic matters, violent crime in Louisville is difficult to interpret and tough to pin down. On the whole, we did seem to have an above average 2016 when compared to the previous 11 years. The heavily localized nature of violent crime in the city seems to suggest individual citizens outside these areas have little reason to fear for their personal safety. When these localized areas are excluded and the remainder of the city is analysed, Louisville’s violent crime has stayed relatively steady over the past 11 years. While 2016 <em>did</em> have a notable uptick in violent crime, more analysis would be needed to determine whether this year was an anomaly or whether this could signal the start of more significant cultural or demographic shifts within the city. Perhaps most significantly overlooked is the change in population over the period from 2005-2016</p>
<p>Whether this marginal trend is cause for alarm is a different matter. City officials may have great cause for concern as several regions of the city have experienced rapid increases in violent crime over the past decade. Fractions of downtown account for a vast majority of all violent crime in the city and that certainly has devastating economic and social impacts on, not only those specific regions, but Louisville as a whole. This is, obviously, a very rough sketch of the violent crime landscape, but with further analysis perhaps smarter plans for law enforcement could be developed.</p>
<p>It should be noted that this is my first dive into crime data. Therefore, many conventions for dealing with data of this sort have certainly been overlooked. Blame the researcher, not the data itself. Additionally, it should be noted that this report can only address crimes contained in the data set. Put bluntly, it is common knowledge that certain crimes–for instance, rape–often go unreported. Sadly, as far as I could gather, this is just something inherent to crime data sets. With that said, it is important to take all of this analysis with a grain of salt and treat it more as a guideline, rather than a ground truth.</p>
<p>Stay tuned for part two where I begin pilfering the dataset for insight into Louisville’s theft problem.</p>
<p>The full code used to generate this report can be found <a href="https://raw.githubusercontent.com/houlad/ahoulblog/master/content/post/2017-07-31-exploring-violent-crime-in-louisville.Rmd">here</a>.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>